#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Hello World!" when queried
#    at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get install -y nginx

# Creates the /etc/nginx/html directory, which will serve as the document root directory for Nginx.
mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

ufw allow 'Nginx HTTP'

echo "Hello World!" > /etc/nginx/html/index.html

service nginx start
