#!/usr/bin/env bash
# Run Nginx without errors

# Configure nginx to listen on all active IPs on port 8080
cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx start
sudo pkill nginx
