#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop and "Hi"
# on the 9th iteration

names='Best School'
counter=0

while [ "$counter" -lt 10 ]
do
  if [ "$counter" -eq 8 ]; then
    echo "$names"
    echo "Hi"
  else 
    echo "Best School"
  fi
  (( counter++ ))
done
